import { useI18n } from "@/i18n/i18n";

export const HeroTitle = () => {
  const { t } = useI18n();
  return (
    <div className="items-center box-border caret-transparent flex text-[16.0982px] justify-center justify-self-center leading-[24.1473px] max-w-[2700px] min-h-[auto] min-w-[auto] outline-[3px] relative no-underline align-bottom w-[calc(100%_-_35.1429px)] mx-auto md:text-[17.7143px] md:leading-[26.5714px] md:w-[calc(100%_-_86.8571px)]">
      <div className="box-border caret-transparent gap-x-[20.1964px] flex flex-col text-[16.0982px] auto-cols-[1fr] leading-[24.1473px] min-h-[auto] min-w-[auto] outline-[3px] relative gap-y-[20.1964px] no-underline align-bottom md:gap-x-[23.4286px] md:text-[17.7143px] md:leading-[26.5714px] md:gap-y-[23.4286px]">
        <div className="box-border caret-transparent text-[16.0982px] justify-self-start leading-[24.1473px] min-h-[auto] min-w-[auto] outline-[3px] no-underline align-bottom md:text-[17.7143px] md:leading-[26.5714px]">
          <div className="box-border caret-transparent flow-root text-[29.375px] font-bold tracking-[-0.29375px] leading-[32.3125px] outline-[3px] no-underline align-bottom font-roslindaledisplaycondensed md:text-[52px] md:tracking-[-0.52px] md:leading-[57.2px] before:accent-auto before:box-border before:caret-transparent before:text-white before:table before:text-[29.375px] before:not-italic before:normal-nums before:font-bold before:tracking-[-0.29375px] before:leading-[32.3125px] before:list-outside before:list-disc before:mb-[-3.81875px] before:outline-[3px] before:pointer-events-auto before:text-start before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-roslindaledisplaycondensed before:md:text-[52px] before:md:tracking-[-0.52px] before:md:leading-[57.2px] before:md:mb-[-6.75375px] after:accent-auto after:box-border after:caret-transparent after:text-white after:table after:text-[29.375px] after:not-italic after:normal-nums after:font-bold after:tracking-[-0.29375px] after:leading-[32.3125px] after:list-outside after:list-disc after:mb-[-4.7px] after:outline-[3px] after:pointer-events-auto after:text-start after:no-underline after:indent-[0px] after:normal-case after:visible after:border-separate after:font-roslindaledisplaycondensed after:md:text-[52px] after:md:tracking-[-0.52px] after:md:leading-[57.2px] after:md:mb-[-8.31375px]">
            {t("hero.top")}
          </div>
        </div>
        <div className="items-center box-border caret-transparent flex flex-col text-[16.0982px] justify-center leading-[24.1473px] min-h-[auto] min-w-[auto] outline-[3px] relative no-underline align-bottom md:text-[17.7143px] md:leading-[26.5714px]">
          <h1 className="box-border caret-transparent flow-root text-[75px] font-bold tracking-[-1.5px] leading-[75px] min-h-[auto] min-w-[auto] outline-[3px] no-underline align-bottom font-roslindaledisplaycondensed md:text-[256px] md:tracking-[-5.12px] md:leading-[256px] before:accent-auto before:box-border before:caret-transparent before:text-white before:table before:text-[75px] before:not-italic before:normal-nums before:font-bold before:tracking-[-1.5px] before:leading-[75px] before:list-outside before:list-disc before:outline-[3px] before:pointer-events-auto before:text-start before:no-underline before:indent-[0px] before:normal-case before:visible before:-mb-1.5 before:border-separate before:font-roslindaledisplaycondensed before:md:text-[256px] before:md:tracking-[-5.12px] before:md:leading-[256px] before:md:mb-[-20.48px] after:accent-auto after:box-border after:caret-transparent after:text-white after:table after:text-[75px] after:not-italic after:normal-nums after:font-bold after:tracking-[-1.5px] after:leading-[75px] after:list-outside after:list-disc after:mb-[-8.25px] after:outline-[3px] after:pointer-events-auto after:text-start after:no-underline after:indent-[0px] after:normal-case after:visible after:border-separate after:font-roslindaledisplaycondensed after:md:text-[256px] after:md:tracking-[-5.12px] after:md:leading-[256px] after:md:mb-[-28.16px]">
            {t("hero.title")}
          </h1>
        </div>
        <div className="box-border caret-transparent text-[16.0982px] justify-self-end leading-[24.1473px] min-h-[auto] min-w-[auto] outline-[3px] text-right no-underline align-bottom md:text-[17.7143px] md:leading-[26.5714px]">
          <div className="box-border caret-transparent flow-root text-[29.375px] font-bold tracking-[-0.29375px] leading-[32.3125px] outline-[3px] no-underline align-bottom font-roslindaledisplaycondensed md:text-[52px] md:tracking-[-0.52px] md:leading-[57.2px] before:accent-auto before:box-border before:caret-transparent before:text-white before:table before:text-[29.375px] before:not-italic before:normal-nums before:font-bold before:tracking-[-0.29375px] before:leading-[32.3125px] before:list-outside before:list-disc before:mb-[-3.81875px] before:outline-[3px] before:pointer-events-auto before:text-right before:no-underline before:indent-[0px] before:normal-case before:visible before:border-separate before:font-roslindaledisplaycondensed before:md:text-[52px] before:md:tracking-[-0.52px] before:md:leading-[57.2px] before:md:mb-[-6.75375px] after:accent-auto after:box-border after:caret-transparent after:text-white after:table after:text-[29.375px] after:not-italic after:normal-nums after:font-bold after:tracking-[-0.29375px] after:leading-[32.3125px] after:list-outside after:list-disc after:mb-[-4.7px] after:outline-[3px] after:pointer-events-auto after:text-right after:no-underline after:indent-[0px] after:normal-case after:visible after:border-separate after:font-roslindaledisplaycondensed after:md:text-[52px] after:md:tracking-[-0.52px] after:md:leading-[57.2px] after:md:mb-[-8.31375px]">
            {t("hero.bottom")}
          </div>
        </div>
      </div>
    </div>
  );
};
